# Generated by Django 3.0.4 on 2020-03-27 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Renter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_as', models.TextField(choices=[('Individual', 'Individual'), ('Company', 'Company')])),
                ('com_ind_name', models.TextField(max_length=500)),
                ('available_from', models.TimeField()),
                ('available_till', models.TimeField()),
                ('eyw_transactionref', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('phoneno', models.IntegerField()),
                ('special_rating', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Car', 'Car'), ('Bike', 'Bike'), ('Bus', 'Bus'), ('Truck', 'Truck'), ('Bicycle', 'Bicycle')])),
                ('manufacturer_company', models.TextField(max_length=100)),
                ('model', models.TextField(max_length=100)),
                ('pickup', models.TextField(max_length=300)),
                ('dropup', models.TextField(max_length=300)),
                ('available_till_time', models.TimeField()),
                ('available_till_date', models.DateField()),
                ('description', models.TextField(max_length=500)),
                ('image', models.TextField()),
                ('priceph', models.IntegerField()),
                ('km_travelled', models.IntegerField()),
                ('slug', models.TextField(default='', unique=True)),
                ('vech_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Renter')),
            ],
        ),
        migrations.CreateModel(
            name='UserAvailable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('location', models.TextField(max_length=200)),
                ('ordered', models.BooleanField(default=False)),
                ('info', models.TextField(max_length=400)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VehicleAvailable')),
                ('renter_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Renter')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemsOrdered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.VehicleAvailable')),
                ('orderedfrom', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='home.Renter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
