# Generated by Django 3.0.4 on 2020-03-27 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleavailable',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
