# Generated by Django 3.0.4 on 2020-03-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200327_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renter',
            old_name='eyw_transactionref',
            new_name='autocode',
        ),
        migrations.AlterField(
            model_name='vehicleavailable',
            name='available_till_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleavailable',
            name='slug',
            field=models.CharField(max_length=500),
        ),
    ]
