# Generated by Django 3.0.4 on 2020-04-11 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200328_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsordered',
            name='free',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemsordered',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.VehicleAvailable'),
        ),
        migrations.AlterField(
            model_name='itemsordered',
            name='orderedfrom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Renter'),
        ),
        migrations.AlterField(
            model_name='vehicleavailable',
            name='type',
            field=models.TextField(),
        ),
    ]
