# Generated by Django 3.0.4 on 2020-04-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200422_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleavailable',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
