# Generated by Django 3.0.4 on 2020-04-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_vehicleavailable_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleavailable',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
