# Generated by Django 3.1.3 on 2020-11-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200427_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('phone_no', models.IntegerField()),
            ],
        ),
    ]
