# Generated by Django 3.1.3 on 2021-02-01 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_consultaion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleavailable',
            name='vech_owner',
        ),
    ]
