# Generated by Django 3.1.3 on 2021-02-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210202_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailable',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
