# Generated by Django 3.1.3 on 2021-02-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20210203_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailable',
            name='location',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
