# Generated by Django 3.1.3 on 2021-02-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210204_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useravailable',
            name='info',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
