# Generated by Django 3.1.3 on 2021-02-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210204_0021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useravailable',
            old_name='ordered',
            new_name='approved',
        ),
    ]
