# Generated by Django 3.1.3 on 2021-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210206_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='useravailable',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
