# Generated by Django 3.1.3 on 2021-02-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_useravailable_rejected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsordered',
            old_name='free',
            new_name='terms',
        ),
    ]
